// Generated by gencpp from file darknet/coordinate.msg
// DO NOT EDIT!


#ifndef DARKNET_MESSAGE_COORDINATE_H
#define DARKNET_MESSAGE_COORDINATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace darknet
{
template <class ContainerAllocator>
struct coordinate_
{
  typedef coordinate_<ContainerAllocator> Type;

  coordinate_()
    : x(0)
    , y(0)  {
    }
  coordinate_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::darknet::coordinate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet::coordinate_<ContainerAllocator> const> ConstPtr;

}; // struct coordinate_

typedef ::darknet::coordinate_<std::allocator<void> > coordinate;

typedef boost::shared_ptr< ::darknet::coordinate > coordinatePtr;
typedef boost::shared_ptr< ::darknet::coordinate const> coordinateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet::coordinate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet::coordinate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::darknet::coordinate_<ContainerAllocator1> & lhs, const ::darknet::coordinate_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::darknet::coordinate_<ContainerAllocator1> & lhs, const ::darknet::coordinate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace darknet

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::darknet::coordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet::coordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet::coordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet::coordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet::coordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet::coordinate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b80853b9dd76da1c3efb4dbc2426fe9";
  }

  static const char* value(const ::darknet::coordinate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b80853b9dd76da1ULL;
  static const uint64_t static_value2 = 0xc3efb4dbc2426fe9ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet/coordinate";
  }

  static const char* value(const ::darknet::coordinate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 x\n"
"\n"
"uint16 y\n"
;
  }

  static const char* value(const ::darknet::coordinate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet::coordinate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordinate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet::coordinate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet::coordinate_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_MESSAGE_COORDINATE_H
